### PR TITLE
this is my first commit

### PR DESCRIPTION
**Pull request by wrichey**
pushing my test/training data (i think? maybe...)

### CODE REVIEW

**Review by CassieW — COMMENTED** [review]
I don't see your files pushed on this commit. Did you add them before push?

**Comment by wrichey** [comment]
I thought I did. I have been very confused but i will try again.

On Sep 21, 2016, at 6:55 PM, Cassie Wang <notifications@github.com<mailto:notifications@github.com>> wrote:

@CassieW commented on this pull request.

I don't see your files pushed on this commit. Did you add them before push?

##

**Comment by wrichey** [comment]
the real document I hope

**Comment by wrichey** [comment]
Attempting to add my files in the data folder?

**Pull request merged**
