### PR TITLE
project revamp and step 2

### PR DESCRIPTION
**Pull request by torablien**
"Step 2 of Class Project: do some research!"

### CODE REVIEW

**Comment by kordjamshidi** [comment]
Great, thanks @torablien ! @CassieW : it seems still the .idea has not been ignored? could you double check, why is that?

**Review by CassieW — COMMENTED** [review]
@torablien : Can  you pull upstream again? The /.idea conflicts should be solved
@kordjamshidi : Just updated .gitignore

**Comment by kordjamshidi** [comment]
Thanks @CassieW !

**Comment by torablien** [comment]
Pulled from upstream and tried again.

**Pull request merged**
