### PR TITLE
created PDF and Word readers and installed relevant dependencies

### PR DESCRIPTION
**Pull request by torablien**

### CODE REVIEW

**Comment by kordjamshidi** [comment]
Hey Niel, could you push your c.9 template?

**Comment by torablien** [comment]
Hi Professor,

I have it pushed here:
GitHub.com/torablien/saul-web-app

I put it here as I was able to make a clear readme and make it easy for people to pull from. Wilson used this and it worked for him.

You can feel to copy it into your GitHub wherever you wish!

Neil

**Comment by kordjamshidi** [comment]
Great, found it, thanks!

**Comment by torablien** [comment]
I am currently getting:

```
    Label     Precision Recall   F1   LCount PCount
---------------------------------------------------
arms-length      73.753 94.613 82.891    297    381
collaborative    30.435  6.542 10.769    107     23
---------------------------------------------------
Accuracy         71.287   -      -      -       404
```

**Comment by torablien** [comment]
Results with filtered words, lexicon, bigrams, and trigrams:

```
    Label     Precision Recall   F1   LCount PCount
---------------------------------------------------
arms-length      77.551 89.562 83.125    297    343
collaborative    49.180 28.037 35.714    107     61
---------------------------------------------------
Accuracy         73.267   -      -      -       404
```

Does not include TF/IDF yet

**Pull request closed without merging**
